# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_auto_20170727_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='moveieID',
            new_name='movieID',
        ),
        migrations.RenameField(
            model_name='showtime',
            old_name='time',
            new_name='theatre',
        ),
        migrations.AddField(
            model_name='showtime',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='user',
        ),
        migrations.AddField(
            model_name='showtime',
            name='user',
            field=models.ManyToManyField(related_name='user_showtimes', to='movies_app.User'),
        ),
    ]
