# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_auto_20170910_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='movieID',
            field=models.CharField(max_length=255),
        ),
    ]
