# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_auto_20170910_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='user',
        ),
        migrations.AddField(
            model_name='showtime',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Users_attending', to='movies_app.User'),
            preserve_default=False,
        ),
    ]
