# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_auto_20170910_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='user',
        ),
        migrations.AddField(
            model_name='showtime',
            name='users',
            field=models.ManyToManyField(related_name='Users_attending', to='movies_app.User'),
        ),
    ]
